version: "3.3"

services:
  test:
    container_name: arc_pls_api
    build: .
    command: bash bash.sh
    restart: unless-stopped
    ports:
      - "48888:8080"
    environment:
      API_KEY: ""
      SITE_ID: "arc.sped0nwen.com"
      PLS_HOST: "pls.sped0nwen.com"
      TZ: "Asia/Shanghai"