version: "3.3"

services:
  test:
    container_name: api
    build: .
    command: bash bash.sh
    restart: unless-stopped
    ports:
      - "48888:8080"
    environment:
      API_KEY: ""
      SITE_ID: "arc.sped0nwen.com"
      UMAMI_HOST: "umami.sped0nwen.com"
      DJANGO_DEBUG: ""
      RUN_ON_HOST: "api.sped0nwen.com"
      CORS_ALLOWED_ORIGINS: "https://arc.sped0nwen.com,http://localhost:1313"
      DJANGO_SECRET_KEY: ""
      TZ: "Asia/Shanghai"
